plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

imagemagick:
  enabled: false

exclude:
  - assets/jupyter/
  - _posts/2023-07-04-jupyter-notebook.md
